#I "packages/NuGet.Core/lib/net40-Client"
#I "packages/IntelliFactory.Core/lib/net45"
#I "packages/IntelliFactory.Build/lib/net45"
#r "NuGet.Core"
#r "IntelliFactory.Core"
#r "IntelliFactory.Build"